export type IconOption = {
  name: string;
  label: string;
  category: string;
};

export const iconOptions: IconOption[] = [
  { name: "wifi", label: "Wi-Fi", category: "Essentials" },
  { name: "ac_unit", label: "Air Conditioning", category: "Essentials" },
  { name: "local_parking", label: "Parking", category: "Essentials" },
  { name: "security", label: "Security", category: "Essentials" },
  { name: "accessible", label: "Accessible", category: "Essentials" },
  { name: "smoke_free", label: "Smoke Free", category: "Essentials" },
  { name: "restaurant", label: "Dining", category: "Dining" },
  { name: "local_cafe", label: "Coffee", category: "Dining" },
  { name: "room_service", label: "Room Service", category: "Dining" },
  { name: "kitchen", label: "Kitchen", category: "Dining" },
  { name: "coffee", label: "Coffee", category: "Dining" },
  { name: "pool", label: "Pool", category: "Leisure" },
  { name: "spa", label: "Spa", category: "Leisure" },
  { name: "fitness_center", label: "Fitness", category: "Leisure" },
  { name: "balcony", label: "Balcony", category: "Leisure" },
  { name: "bathtub", label: "Bathtub", category: "Leisure" },
  { name: "nature", label: "Nature", category: "Leisure" },
  { name: "garden", label: "Garden", category: "Leisure" },
  { name: "work", label: "Workspace", category: "Business" },
  { name: "desk", label: "Desk", category: "Business" },
  { name: "meeting_room", label: "Meeting Room", category: "Business" },
  { name: "laptop", label: "Laptop", category: "Business" },
  { name: "luggage", label: "Luggage", category: "Travel" },
  { name: "directions_car", label: "Car", category: "Travel" },
  { name: "local_taxi", label: "Taxi", category: "Travel" },
  { name: "airport_shuttle", label: "Shuttle", category: "Travel" },
  { name: "bed", label: "Bed", category: "Rooms" },
  { name: "king_bed", label: "King Bed", category: "Rooms" },
  { name: "single_bed", label: "Single Bed", category: "Rooms" },
  { name: "weekend", label: "Lounge", category: "Rooms" },
  { name: "tv", label: "TV", category: "Rooms" },
  { name: "connected_tv", label: "Streaming TV", category: "Rooms" },
  { name: "stairs", label: "Stairs", category: "Rooms" },
  { name: "elevator", label: "Elevator", category: "Rooms" },
  { name: "cleaning_services", label: "Cleaning", category: "Housekeeping" },
  { name: "laundry", label: "Laundry", category: "Housekeeping" },
  { name: "dry_cleaning", label: "Dry Cleaning", category: "Housekeeping" },
  { name: "iron", label: "Iron", category: "Housekeeping" },
  { name: "verified", label: "Verified", category: "Trust" },
  { name: "workspace_premium", label: "Premium", category: "Trust" },
  { name: "check_circle", label: "Included", category: "Trust" },
  { name: "shield", label: "Shield", category: "Trust" },
];
