insert into rooms (
  slug,
  name,
  description,
  price_per_night,
  bed_type,
  max_guests,
  room_type,
  view_type,
  size,
  images,
  amenities,
  features,
  cancellation_policy,
  is_active,
  availability_status,
  availability_blocks,
  featured
)
values
  (
    'the-silt-suite',
    'The Silt Suite',
    'Standard suite with city views, featuring high-quality linens and a desk area.',
    650,
    '1 King',
    2,
    'Suite',
    'City View',
    '35 sqm',
    '["https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1560449752-3f3f3d1b4d0c?auto=format&fit=crop&w=1200&q=80"]'::jsonb,
    '["A/C","Wi-Fi","Mini Bar"]'::jsonb,
    '[{"label":"1 King","icon":"bed"},{"label":"A/C","icon":"ac_unit"},{"label":"Wi-Fi","icon":"wifi"}]'::jsonb,
    'Free cancellation up to 48 hours before check-in',
    true,
    'available',
    '[]'::jsonb,
    true
  ),
  (
    'modern-retreat',
    'Modern Retreat',
    'Elegant suite with stone finishes and modern amenities for ultimate comfort.',
    750,
    '1 Queen',
    2,
    'Suite',
    'Garden View',
    '38 sqm',
    '["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1560449752-3f3f3d1b4d0c?auto=format&fit=crop&w=1200&q=80"]'::jsonb,
    '["A/C","Wi-Fi","Bathtub"]'::jsonb,
    '[{"label":"1 Queen","icon":"bed"},{"label":"Bathtub","icon":"bathtub"},{"label":"Wi-Fi","icon":"wifi"}]'::jsonb,
    'Free cancellation up to 48 hours before check-in',
    true,
    'available',
    '[]'::jsonb,
    false
  ),
  (
    'spacious-living',
    'Spacious Living',
    'Spacious suite with separate living area, perfect for families or extended stays.',
    850,
    '2 Queen',
    4,
    'Deluxe',
    'Garden View',
    '48 sqm',
    '["https://images.unsplash.com/photo-1560449752-3f3f3d1b4d0c?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80"]'::jsonb,
    '["A/C","Wi-Fi","Living Area","Mini Bar"]'::jsonb,
    '[{"label":"2 Queen","icon":"bed"},{"label":"Living Area","icon":"weekend"},{"label":"Mini Bar","icon":"local_bar"}]'::jsonb,
    'Free cancellation up to 48 hours before check-in',
    true,
    'available',
    '[]'::jsonb,
    true
  ),
  (
    'silt-suite-ii',
    'Silt Suite II',
    'Comfortable suite with modern furnishings and excellent city views.',
    700,
    '1 King',
    2,
    'Suite',
    'City View',
    '36 sqm',
    '["https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80"]'::jsonb,
    '["A/C","Wi-Fi","Desk"]'::jsonb,
    '[{"label":"1 King","icon":"bed"},{"label":"Desk","icon":"desk"},{"label":"Wi-Fi","icon":"wifi"}]'::jsonb,
    'Free cancellation up to 48 hours before check-in',
    true,
    'available',
    '[]'::jsonb,
    false
  ),
  (
    'basalt-retreat',
    'Basalt Retreat',
    'Premium suite with private balcony overlooking the pool area.',
    900,
    '1 King',
    2,
    'Premium',
    'Pool View',
    '42 sqm',
    '["https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80"]'::jsonb,
    '["A/C","Wi-Fi","Mini Bar","Balcony"]'::jsonb,
    '[{"label":"1 King","icon":"bed"},{"label":"Balcony","icon":"balcony"},{"label":"Mini Bar","icon":"local_bar"}]'::jsonb,
    'Free cancellation up to 48 hours before check-in',
    true,
    'available',
    '[]'::jsonb,
    true
  ),
  (
    'lodge-suite',
    'Lodge Suite',
    'Deluxe suite with traditional lodge aesthetics and modern comfort.',
    800,
    '1 King',
    2,
    'Deluxe',
    'Garden View',
    '40 sqm',
    '["https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1560449752-3f3f3d1b4d0c?auto=format&fit=crop&w=1200&q=80"]'::jsonb,
    '["A/C","Wi-Fi","Mini Bar","Sitting Area"]'::jsonb,
    '[{"label":"1 King","icon":"bed"},{"label":"Sitting Area","icon":"weekend"},{"label":"Mini Bar","icon":"local_bar"}]'::jsonb,
    'Free cancellation up to 48 hours before check-in',
    true,
    'available',
    '[]'::jsonb,
    false
  ),
  (
    'terrace-twin',
    'Terrace Twin',
    'Twin layout with a small terrace, ideal for travel companions or longer city stays.',
    720,
    '2 Queen',
    4,
    'Suite',
    'City View',
    '44 sqm',
    '["https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1560449752-3f3f3d1b4d0c?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80"]'::jsonb,
    '["A/C","Wi-Fi","Mini Bar","Balcony"]'::jsonb,
    '[{"label":"2 Queen","icon":"bed"},{"label":"Balcony","icon":"balcony"},{"label":"Wi-Fi","icon":"wifi"}]'::jsonb,
    'Free cancellation up to 48 hours before check-in',
    true,
    'available',
    '[]'::jsonb,
    false
  ),
  (
    'travelling-executive',
    'Travelling Executive',
    'Premium room with refined finishes and a workspace built for business travelers.',
    980,
    '1 Queen',
    2,
    'Premium',
    'Pool View',
    '39 sqm',
    '["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80"]'::jsonb,
    '["A/C","Wi-Fi","Bathtub","Desk"]'::jsonb,
    '[{"label":"1 Queen","icon":"bed"},{"label":"Bathtub","icon":"bathtub"},{"label":"Desk","icon":"desk"}]'::jsonb,
    'Free cancellation up to 48 hours before check-in',
    true,
    'available',
    '[]'::jsonb,
    false
  ),
  (
    'horizon-family',
    'Horizon Family',
    'A larger family-friendly suite with room to relax, gather, and unwind.',
    950,
    '2 Queen',
    4,
    'Deluxe',
    'Garden View',
    '52 sqm',
    '["https://images.unsplash.com/photo-1560449752-3f3f3d1b4d0c?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80"]'::jsonb,
    '["A/C","Wi-Fi","Living Area","Balcony"]'::jsonb,
    '[{"label":"2 Queen","icon":"bed"},{"label":"Living Area","icon":"weekend"},{"label":"Balcony","icon":"balcony"}]'::jsonb,
    'Free cancellation up to 48 hours before check-in',
    true,
    'available',
    '[]'::jsonb,
    false
  ),
  (
    'courtyard-king',
    'Courtyard King',
    'Quiet king room overlooking the inner courtyard, ideal for short city stays.',
    670,
    '1 King',
    2,
    'Suite',
    'Garden View',
    '34 sqm',
    '["https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1560449752-3f3f3d1b4d0c?auto=format&fit=crop&w=1200&q=80"]'::jsonb,
    '["A/C","Wi-Fi","Desk"]'::jsonb,
    '[{"label":"1 King","icon":"bed"},{"label":"Desk","icon":"desk"},{"label":"Wi-Fi","icon":"wifi"}]'::jsonb,
    'Free cancellation up to 48 hours before check-in',
    true,
    'available',
    '[]'::jsonb,
    false
  ),
  (
    'sunset-loft',
    'Sunset Loft',
    'A bright loft-style room with a balcony and extra lounging space.',
    1020,
    '2 Queen',
    4,
    'Premium',
    'Pool View',
    '56 sqm',
    '["https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1560449752-3f3f3d1b4d0c?auto=format&fit=crop&w=1200&q=80"]'::jsonb,
    '["A/C","Wi-Fi","Balcony","Living Area"]'::jsonb,
    '[{"label":"2 Queen","icon":"bed"},{"label":"Balcony","icon":"balcony"},{"label":"Living Area","icon":"weekend"}]'::jsonb,
    'Free cancellation up to 48 hours before check-in',
    true,
    'available',
    '[]'::jsonb,
    true
  ),
  (
    'garden-suite',
    'Garden Suite',
    'A calm suite surrounded by greenery, with a spacious layout and soft lighting.',
    880,
    '1 Queen',
    2,
    'Deluxe',
    'Garden View',
    '41 sqm',
    '["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80"]'::jsonb,
    '["A/C","Wi-Fi","Mini Bar","Bathtub"]'::jsonb,
    '[{"label":"1 Queen","icon":"bed"},{"label":"Mini Bar","icon":"local_bar"},{"label":"Bathtub","icon":"bathtub"}]'::jsonb,
    'Free cancellation up to 48 hours before check-in',
    true,
    'available',
    '[]'::jsonb,
    false
  )
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  price_per_night = excluded.price_per_night,
  bed_type = excluded.bed_type,
  max_guests = excluded.max_guests,
  room_type = excluded.room_type,
  view_type = excluded.view_type,
  size = excluded.size,
  images = excluded.images,
  amenities = excluded.amenities,
  features = excluded.features,
  cancellation_policy = excluded.cancellation_policy,
  is_active = excluded.is_active,
  availability_status = excluded.availability_status,
  availability_blocks = excluded.availability_blocks,
  featured = excluded.featured;
